export { default as mywork } from './mywork'
export { default as system } from './system'
export { default as navigation } from './navigation'
export { default as vehicleFlow } from './vehicleFlow'

export { default as fireDataAlarm } from './fireDataAlarm'
export { default as curing } from './curing'
export { default as environmentDataAlarm } from './environmentDataAlarm'
export { default as videoEventDetection } from './videoEventDetection'
export { default as informationBoard } from './informationBoard'
export { default as numList } from './numList'
